<a href="https://colab.research.google.com/github/Aarush29/hello-world-/blob/main/Copy_of_data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [8]:
dataset = pd.read_csv('Data.csv')    #read_csv is a function of pandas that will input the name of the dataset which is given as Data.csv 
# x = dependent variable ; in the given data it is the first three columns 
# y = independent variable ; it is the last column 
X = dataset.iloc[:, :-1].values      # iloc[] is function of panda that locate indexes from the column we hace to extract.[]is used as [rows:columns]; here all the rows are counted so ' :'.
                                     # ', :-1" means from 0 (included) to -1(excluded) which excludes the last column
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [4]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [5]:
#one way of taking care of missing data is by REMOVING THEM. only used if 1% data is missing.
#2nd way : by putting the avg value of data(s) on the missing value.
from sklearn.impute import SimpleImputer #from scitechkearn lib import the class simpleimputer
imputer = SimpleImputer(missing_values=np.nan , strategy='mean')      #np.nan means that ' we want to replace all missing values.
                                                                      #strategy=mean means 'we will replace all missing values by mean
#fit method= bridge between imputer and matrix of features (X)
#transform method = it will transform the missing values 
imputer.fit(X[:,1:3])
# imputer.transform(x[:,1:3])
#after transform method, we need to update our data; that is done by taking the range of X with x as well and making the whole transform statemnt the value of that x (with range)
(X[:,1:3]) = imputer.transform(X[:,1:3]) 

In [6]:
print (X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
#ct.fit_transform(X)
X=np.array(ct.fit_transform(X)) 


In [10]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 nan 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [11]:

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()  #we dont need enter anything in the argument since we are taking the whole y as a target
y= le.fit_transform(y) 

In [12]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=1)



In [14]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [15]:
print(X_train)

[[0.0 0.0 1.0 nan 52000.0]
 [0.0 1.0 0.0 40.0 nan]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [16]:
print(y_test)

[0 1]


In [17]:
print(y_train)

[0 1 0 0 1 1 0 1]


## Feature Scaling

In [18]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler() #no need for arguments
X_train[:,3:] = sc.fit_transform(X_train[:,3:])
X_test[:,3:] = sc.transform(X_test[:,3:])


In [19]:
print(X_train)

[[0.0 0.0 1.0 nan -1.0182239953527132]
 [0.0 1.0 0.0 -0.038910211282047996 nan]
 [1.0 0.0 0.0 0.5058327466666259 0.583476671494251]
 [0.0 0.0 1.0 -0.3112816902563849 -0.2974586952715793]
 [0.0 0.0 1.0 -1.809324824615238 -1.3385641287221062]
 [1.0 0.0 0.0 1.0505757046152997 1.1440719048906884]
 [0.0 1.0 0.0 1.3229471835896367 1.4644120382600814]
 [1.0 0.0 0.0 -0.7198389087178904 -0.537713795298624]]


In [ ]:
print(X_test)